// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = function(url) {
    return new Promise(function(resolve) {
      var image;
      image = new Image;
      image.onload = function() {
        return resolve(image);
      };
      return image.src = url;
    });
  };

}).call(this);
